export interface Category {
  id: string;
  name: string;
}

export interface Topic {
  id: string;
  categoryId: string;
  title: string;
}

export const categories: Category[] = [
  { id: "tech", name: "Technology & AI" },
  { id: "bio", name: "Biology & Genetics" },
  { id: "phil", name: "Philosophy" },
  { id: "psych", name: "Psychology" },
  { id: "astro", name: "Astronomy & Physics" },
  { id: "cs", name: "Computer Science" },
  { id: "hist", name: "History & Civilization" },
  { id: "econ", name: "Economics & Finance" },
  { id: "math", name: "Mathematics & Logic" },
  { id: "art", name: "Art & Architecture" },
  { id: "lit", name: "Literature & Language" },
  { id: "strat", name: "Strategy & Game Theory" },
  { id: "soc", name: "Sociology & Culture" },
  { id: "eco", name: "Environment & Ecology" },
  { id: "med", name: "Medicine & Health" },
  { id: "pol", name: "Political Science" },
  { id: "law", name: "Law & Ethics" },
  { id: "mus", name: "Music & Sound" },
  { id: "pop", name: "Entertainment & Media" },
  { id: "prod", name: "Productivity & Systems" },
  { id: "webdev", name: "Web Engineering & Architecture" },
  { id: "algo", name: "Algorithms & Computation" },
  { id: "cyber", name: "Cybersecurity & Privacy" },
  { id: "web3", name: "Blockchain & Decentralization" },
  { id: "travel", name: "Geography & Urbanism" },
  { id: "game", name: "Game Design & Mechanics" },
  { id: "food", name: "Food Science & Gastronomy" },
  { id: "myth", name: "Mythology & Folklore" },
  { id: "biz", name: "Startups & Innovation" },
  { id: "space", name: "Aerospace & Engineering" }
];

export const topics: Topic[] = [
  // --- 1. TECHNOLOGY & AI ---
  { id: "tech-1", categoryId: "tech", title: "The implications of Artificial General Intelligence (AGI)" },
  { id: "tech-2", categoryId: "tech", title: "How quantum computing will break modern encryption" },
  { id: "tech-3", categoryId: "tech", title: "The psychological impact of algorithmic infinite scrolling" },
  { id: "tech-4", categoryId: "tech", title: "The ethics of open-source facial recognition models" },
  { id: "tech-5", categoryId: "tech", title: "Brain-computer interfaces and the future of human output" },
  { id: "tech-6", categoryId: "tech", title: "The environmental cost of training large language models" },
  { id: "tech-7", categoryId: "tech", title: "Deepfakes and the erosion of digital trust" },
  { id: "tech-8", categoryId: "tech", title: "The feasibility of fully autonomous smart cities" },
  { id: "tech-9", categoryId: "tech", title: "Digital immortality: Uploading consciousness to the cloud" },
  { id: "tech-10", categoryId: "tech", title: "The role of generative AI in replacing creative industries" },
  { id: "tech-11", categoryId: "tech", title: "Augmented reality vs. Virtual reality: Which wins the decade?" },
  { id: "tech-12", categoryId: "tech", title: "The vulnerabilities of the global submarine internet cable network" },
  { id: "tech-13", categoryId: "tech", title: "How 6G networks will change IoT architecture" },
  { id: "tech-14", categoryId: "tech", title: "The militarization of commercial drone technology" },
  { id: "tech-15", categoryId: "tech", title: "Data sovereignty in the age of global cloud providers" },

  // --- 2. BIOLOGY & GENETICS ---
  { id: "bio-1", categoryId: "bio", title: "CRISPR and the ethical boundaries of human gene editing" },
  { id: "bio-2", categoryId: "bio", title: "The intelligence and communication of mycelial networks" },
  { id: "bio-3", categoryId: "bio", title: "How the human microbiome dictates daily mood and behavior" },
  { id: "bio-4", categoryId: "bio", title: "Epigenetics: How trauma is inherited across generations" },
  { id: "bio-5", categoryId: "bio", title: "The biological mechanisms of biological immortality in jellyfish" },
  { id: "bio-6", categoryId: "bio", title: "Synthetic biology and the creation of artificial life" },
  { id: "bio-7", categoryId: "bio", title: "The evolutionary purpose of sleep across species" },
  { id: "bio-8", categoryId: "bio", title: "Antibiotic resistance: The post-antibiotic apocalypse" },
  { id: "bio-9", categoryId: "bio", title: "The role of bacteriophages in modern medicine" },
  { id: "bio-10", categoryId: "bio", title: "De-extinction: The science of bringing back the Woolly Mammoth" },
  { id: "bio-11", categoryId: "bio", title: "The impact of microplastics on human cellular health" },
  { id: "bio-12", categoryId: "bio", title: "Neuroplasticity and the brain's ability to rewire itself" },
  { id: "bio-13", categoryId: "bio", title: "The evolutionary advantage of altruism" },
  { id: "bio-14", categoryId: "bio", title: "Circadian rhythms and chronobiology" },
  { id: "bio-15", categoryId: "bio", title: "The limits of human biological endurance" },

  // --- 3. PHILOSOPHY ---
  { id: "phil-1", categoryId: "phil", title: "Determinism vs. Free Will in a physics-driven universe" },
  { id: "phil-2", categoryId: "phil", title: "Nihilism vs. Absurdism in navigating modern society" },
  { id: "phil-3", categoryId: "phil", title: "The Ship of Theseus and the concept of human identity" },
  { id: "phil-4", categoryId: "phil", title: "Utilitarianism and the Trolley Problem in AI programming" },
  { id: "phil-5", categoryId: "phil", title: "The Allegory of the Cave in the era of social media" },
  { id: "phil-6", categoryId: "phil", title: "Stoicism as a practical framework for digital anxiety" },
  { id: "phil-7", categoryId: "phil", title: "The Simulation Hypothesis: Are we living in a construct?" },
  { id: "phil-8", categoryId: "phil", title: "Existentialism and the burden of total freedom" },
  { id: "phil-9", categoryId: "phil", title: "The paradox of tolerance in a democratic society" },
  { id: "phil-10", categoryId: "phil", title: "Machiavellianism in modern corporate culture" },
  { id: "phil-11", categoryId: "phil", title: "Solipsism: The impossibility of proving other minds exist" },
  { id: "phil-12", categoryId: "phil", title: "The concept of 'The Übermensch' by Friedrich Nietzsche" },
  { id: "phil-13", categoryId: "phil", title: "Panpsychism: Is consciousness a fundamental property of matter?" },
  { id: "phil-14", categoryId: "phil", title: "The categorical imperative of Immanuel Kant" },
  { id: "phil-15", categoryId: "phil", title: "Epistemology: How do we actually know what we know?" },

  // --- 4. PSYCHOLOGY ---
  { id: "psych-1", categoryId: "psych", title: "The Dunning-Kruger effect in the information age" },
  { id: "psych-2", categoryId: "psych", title: "Cognitive dissonance and political tribalism" },
  { id: "psych-3", categoryId: "psych", title: "The bystander effect in digital communities" },
  { id: "psych-4", categoryId: "psych", title: "The psychology of flow states and deep work" },
  { id: "psych-5", categoryId: "psych", title: "Operant conditioning in mobile app design" },
  { id: "psych-6", categoryId: "psych", title: "The impact of parasocial relationships on mental health" },
  { id: "psych-7", categoryId: "psych", title: "The dark triad of personality traits" },
  { id: "psych-8", categoryId: "psych", title: "Imposter syndrome in high-achieving environments" },
  { id: "psych-9", categoryId: "psych", title: "The validity of the Myers-Briggs Type Indicator (MBTI)" },
  { id: "psych-10", categoryId: "psych", title: "False memory syndrome and the unreliability of eyewitnesses" },
  { id: "psych-11", categoryId: "psych", title: "The evolutionary basis for human phobias" },
  { id: "psych-12", categoryId: "psych", title: "Choice overload and decision fatigue" },
  { id: "psych-13", categoryId: "psych", title: "The psychological mechanics of addiction" },
  { id: "psych-14", categoryId: "psych", title: "Groupthink and the loss of individual accountability" },
  { id: "psych-15", categoryId: "psych", title: "The placebo and nocebo effects on physical health" },

  // --- 5. ASTRONOMY & PHYSICS ---
  { id: "astro-1", categoryId: "astro", title: "The Grandfather Paradox and the theoretical physics of time travel" },
  { id: "astro-2", categoryId: "astro", title: "The mathematical probability and implications of the Multiverse" },
  { id: "astro-3", categoryId: "astro", title: "String theory and the existence of parallel universes" },
  { id: "astro-4", categoryId: "astro", title: "The Fermi Paradox: Where are all the aliens?" },
  { id: "astro-5", categoryId: "astro", title: "Dark matter, dark energy, and the expanding universe" },
  { id: "astro-6", categoryId: "astro", title: "The information paradox of black holes" },
  { id: "astro-7", categoryId: "astro", title: "Quantum entanglement and 'spooky action at a distance'" },
  { id: "astro-8", categoryId: "astro", title: "The feasibility of building a Dyson Sphere" },
  { id: "astro-9", categoryId: "astro", title: "The concept of entropy and the inevitable heat death of the universe" },
  { id: "astro-10", categoryId: "astro", title: "Neutron stars, pulsars, and the densest matter in the cosmos" },
  { id: "astro-11", categoryId: "astro", title: "The challenges of colonizing Mars" },
  { id: "astro-12", categoryId: "astro", title: "The Search for Extraterrestrial Intelligence (SETI)" },
  { id: "astro-13", categoryId: "astro", title: "Relativity and time dilation near massive objects" },
  { id: "astro-14", categoryId: "astro", title: "The physics of warp drives and faster-than-light travel" },
  { id: "astro-15", categoryId: "astro", title: "The birth and life cycle of a star" },

  // --- 6. COMPUTER SCIENCE ---
  { id: "cs-1", categoryId: "cs", title: "Graph theory and its applications in social network algorithms" },
  { id: "cs-2", categoryId: "cs", title: "The mechanics of zero-knowledge proofs in modern cryptography" },
  { id: "cs-3", categoryId: "cs", title: "Real-time state synchronization via WebSocket connections" },
  { id: "cs-4", categoryId: "cs", title: "The importance of strict WCAG compliance in accessible web interfaces" },
  { id: "cs-5", categoryId: "cs", title: "Time-space complexity optimization in competitive programming" },
  { id: "cs-6", categoryId: "cs", title: "The evolution of server-side rendering vs. client-side routing" },
  { id: "cs-7", categoryId: "cs", title: "Relational algebra and the foundation of SQL databases" },
  { id: "cs-8", categoryId: "cs", title: "The architecture and security flaws of operating system kernels" },
  { id: "cs-9", categoryId: "cs", title: "Distributed consensus algorithms in decentralized networks" },
  { id: "cs-10", categoryId: "cs", title: "The halting problem and the limits of computation" },
  { id: "cs-11", categoryId: "cs", title: "Garbage collection algorithms and memory leak prevention" },
  { id: "cs-12", categoryId: "cs", title: "The principles of eventual consistency in NoSQL databases" },
  { id: "cs-13", categoryId: "cs", title: "Man-in-the-middle attacks and network security architecture" },
  { id: "cs-14", categoryId: "cs", title: "The shift from monolithic architectures to microservices" },
  { id: "cs-15", categoryId: "cs", title: "The role of heuristics in solving NP-hard problems" },

  // --- 7. HISTORY & CIVILIZATION ---
  { id: "hist-1", categoryId: "hist", title: "The Bronze Age Collapse and the fragility of global trade" },
  { id: "hist-2", categoryId: "hist", title: "The library of Alexandria and the loss of ancient knowledge" },
  { id: "hist-3", categoryId: "hist", title: "The geopolitical impact of the Silk Road" },
  { id: "hist-4", categoryId: "hist", title: "The root causes of the French Revolution" },
  { id: "hist-5", categoryId: "hist", title: "The tactical brilliance of the Mongol Empire" },
  { id: "hist-6", categoryId: "hist", title: "The Industrial Revolution's impact on social classes" },
  { id: "hist-7", categoryId: "hist", title: "The real history of piracy in the Caribbean" },
  { id: "hist-8", categoryId: "hist", title: "The Cold War space race as a proxy conflict" },
  { id: "hist-9", categoryId: "hist", title: "The fall of the Western Roman Empire" },
  { id: "hist-10", categoryId: "hist", title: "The architectural engineering of the Egyptian Pyramids" },
  { id: "hist-11", categoryId: "hist", title: "The samurai code of Bushido during the Edo period" },
  { id: "hist-12", categoryId: "hist", title: "The history and impact of the printing press" },
  { id: "hist-13", categoryId: "hist", title: "The transatlantic slave trade and its economic foundations" },
  { id: "hist-14", categoryId: "hist", title: "The cryptography of the Enigma Machine in WWII" },
  { id: "hist-15", categoryId: "hist", title: "The partition of India and its lasting consequences" },

  // --- 8. ECONOMICS & FINANCE ---
  { id: "econ-1", categoryId: "econ", title: "The mechanics of quadratic funding for decentralized public goods" },
  { id: "econ-2", categoryId: "econ", title: "Fiat currency and the risks of hyperinflation" },
  { id: "econ-3", categoryId: "econ", title: "The concept of Universal Basic Income (UBI)" },
  { id: "econ-4", categoryId: "econ", title: "The 2008 subprime mortgage crisis explained" },
  { id: "econ-5", categoryId: "econ", title: "The economic principles of supply chain logistics" },
  { id: "econ-6", categoryId: "econ", title: "Behavioral economics: Why humans make irrational financial choices" },
  { id: "econ-7", categoryId: "econ", title: "The gig economy and the erosion of worker benefits" },
  { id: "econ-8", categoryId: "econ", title: "The Cantillon Effect: How money printing affects wealth disparity" },
  { id: "econ-9", categoryId: "econ", title: "Microfinance and poverty alleviation in developing nations" },
  { id: "econ-10", categoryId: "econ", title: "The economics of attention in the digital age" },
  { id: "econ-11", categoryId: "econ", title: "GameStop, short squeezes, and decentralized retail investing" },
  { id: "econ-12", categoryId: "econ", title: "The implications of transitioning to a cashless society" },
  { id: "econ-13", categoryId: "econ", title: "Planned obsolescence in consumer electronics" },
  { id: "econ-14", categoryId: "econ", title: "The tragedy of the commons in environmental economics" },
  { id: "econ-15", categoryId: "econ", title: "How central banks manipulate interest rates to control inflation" },

  // --- 9. MATHEMATICS & LOGIC ---
  { id: "math-1", categoryId: "math", title: "The Riemann Hypothesis and the distribution of prime numbers" },
  { id: "math-2", categoryId: "math", title: "Gödel's Incompleteness Theorems" },
  { id: "math-3", categoryId: "math", title: "The Monty Hall problem and counter-intuitive probability" },
  { id: "math-4", categoryId: "math", title: "Fractals and the mathematics of nature" },
  { id: "math-5", categoryId: "math", title: "The concept of infinity and Cantor's different sizes of infinity" },
  { id: "math-6", categoryId: "math", title: "The Golden Ratio in art, architecture, and biology" },
  { id: "math-7", categoryId: "math", title: "Chaos theory and the butterfly effect" },
  { id: "math-8", categoryId: "math", title: "P vs NP: The greatest unsolved problem in computer science" },
  { id: "math-9", categoryId: "math", title: "The Banach-Tarski paradox" },
  { id: "math-10", categoryId: "math", title: "Bayesian probability vs. Frequentist probability" },
  { id: "math-11", categoryId: "math", title: "The mathematics of cryptography and prime factorization" },
  { id: "math-12", categoryId: "math", title: "Zeno's paradoxes of motion" },
  { id: "math-13", categoryId: "math", title: "Topology and the mathematics of continuous deformation" },
  { id: "math-14", categoryId: "math", title: "The Fibonacci sequence in the natural world" },
  { id: "math-15", categoryId: "math", title: "Game theory matrices and zero-sum games" },

  // --- 10. ART & ARCHITECTURE ---
  { id: "art-1", categoryId: "art", title: "Brutalism and the philosophy of concrete architecture" },
  { id: "art-2", categoryId: "art", title: "The surrealist movement and the exploration of the unconscious" },
  { id: "art-3", categoryId: "art", title: "The transition from Renaissance to Baroque art" },
  { id: "art-4", categoryId: "art", title: "The psychology of color theory in marketing design" },
  { id: "art-5", categoryId: "art", title: "The Bauhaus movement and modern industrial design" },
  { id: "art-6", categoryId: "art", title: "The impact of photography on traditional painting" },
  { id: "art-7", categoryId: "art", title: "Gothic architecture and the engineering of flying buttresses" },
  { id: "art-8", categoryId: "art", title: "The commercialization of street art and graffiti" },
  { id: "art-9", categoryId: "art", title: "Minimalism as an aesthetic and cultural rebellion" },
  { id: "art-10", categoryId: "art", title: "The cultural significance of Islamic geometric patterns" },
  { id: "art-11", categoryId: "art", title: "Art Deco and the visual language of the 1920s" },
  { id: "art-12", categoryId: "art", title: "The use of negative space in Japanese design (Ma)" },
  { id: "art-13", categoryId: "art", title: "The ethics of AI-generated art and copyright" },
  { id: "art-14", categoryId: "art", title: "The evolution of typography in the digital age" },
  { id: "art-15", categoryId: "art", title: "The role of public monuments in shaping historical memory" },

  // --- 11. LITERATURE & LANGUAGE ---
  { id: "lit-1", categoryId: "lit", title: "The Sapir-Whorf hypothesis: Does language shape thought?" },
  { id: "lit-2", categoryId: "lit", title: "The evolution of the cyberpunk genre in sci-fi literature" },
  { id: "lit-3", categoryId: "lit", title: "The archetype of the tragic hero in Shakespearean plays" },
  { id: "lit-4", categoryId: "lit", title: "Dystopian literature as a reflection of contemporary anxieties" },
  { id: "lit-5", categoryId: "lit", title: "The death of the author in literary criticism" },
  { id: "lit-6", categoryId: "lit", title: "The preservation of dying indigenous languages" },
  { id: "lit-7", categoryId: "lit", title: "The structure of the Hero's Journey (Monomyth)" },
  { id: "lit-8", categoryId: "lit", title: "The use of unreliable narrators in modern fiction" },
  { id: "lit-9", categoryId: "lit", title: "The impact of texting and internet slang on linguistic evolution" },
  { id: "lit-10", categoryId: "lit", title: "Magical realism in Latin American literature" },
  { id: "lit-11", categoryId: "lit", title: "The transition from oral tradition to written histories" },
  { id: "lit-12", categoryId: "lit", title: "The challenge of translating idioms across distinct cultures" },
  { id: "lit-13", categoryId: "lit", title: "The significance of world-building in epic fantasy" },
  { id: "lit-14", categoryId: "lit", title: "Satire vs. Sarcasm: Tools of social critique" },
  { id: "lit-15", categoryId: "lit", title: "The linguistics of constructed languages (Conlangs like Esperanto)" },

  // --- 12. STRATEGY & GAME THEORY ---
  { id: "strat-1", categoryId: "strat", title: "Algorithmic thinking and pattern recognition in speedcubing" },
  { id: "strat-2", categoryId: "strat", title: "The psychology of time pressure in Blitz and Bullet chess" },
  { id: "strat-3", categoryId: "strat", title: "The Nash Equilibrium in everyday decision making" },
  { id: "strat-4", categoryId: "strat", title: "The Prisoner's Dilemma and mutual cooperation" },
  { id: "strat-5", categoryId: "strat", title: "Minimax algorithms in zero-sum game engines" },
  { id: "strat-6", categoryId: "strat", title: "The concept of 'meta' (Most Effective Tactic Available) in competitive gaming" },
  { id: "strat-7", categoryId: "strat", title: "Sun Tzu's Art of War applied to modern business" },
  { id: "strat-8", categoryId: "strat", title: "The OODA Loop (Observe, Orient, Decide, Act) in crisis management" },
  { id: "strat-9", categoryId: "strat", title: "Game theory in geopolitical nuclear deterrence" },
  { id: "strat-10", categoryId: "strat", title: "The Monty Carlo tree search in modern AI systems" },
  { id: "strat-11", categoryId: "strat", title: "Risk management and expected value in professional poker" },
  { id: "strat-12", categoryId: "strat", title: "The first-mover advantage vs. the fast-follower strategy" },
  { id: "strat-13", categoryId: "strat", title: "Positional advantages vs. material advantages in abstract strategy games" },
  { id: "strat-14", categoryId: "strat", title: "The concept of 'tilt' and emotional regulation in competition" },
  { id: "strat-15", categoryId: "strat", title: "Asymmetric warfare and resource allocation" },

  // --- 13. SOCIOLOGY & CULTURE ---
  { id: "soc-1", categoryId: "soc", title: "The impact of algorithmic echo chambers on political polarization" },
  { id: "soc-2", categoryId: "soc", title: "The gentrification of urban neighborhoods" },
  { id: "soc-3", categoryId: "soc", title: "The sociology of fashion and signaling theory" },
  { id: "soc-4", categoryId: "soc", title: "Cancel culture and the mechanics of public shaming" },
  { id: "soc-5", categoryId: "soc", title: "The commodification of counter-cultures" },
  { id: "soc-6", categoryId: "soc", title: "The shift from nuclear families to alternative community structures" },
  { id: "soc-7", categoryId: "soc", title: "Cult dynamics and the psychology of high-control groups" },
  { id: "soc-8", categoryId: "soc", title: "The impact of remote work on social cohesion" },
  { id: "soc-9", categoryId: "soc", title: "The concept of 'Third Places' and their disappearance" },
  { id: "soc-10", categoryId: "soc", title: "Hustle culture and the glorification of burnout" },
  { id: "soc-11", categoryId: "soc", title: "The digital divide and structural inequality" },
  { id: "soc-12", categoryId: "soc", title: "Memes as a primary form of cultural transmission" },
  { id: "soc-13", categoryId: "soc", title: "The social implications of declining global birth rates" },
  { id: "soc-14", categoryId: "soc", title: "The evolution of tipping culture in the service industry" },
  { id: "soc-15", categoryId: "soc", title: "Conspicuous consumption and wealth signaling" },

  // --- 14. ENVIRONMENT & ECOLOGY ---
  { id: "eco-1", categoryId: "eco", title: "The role of apex predators in maintaining ecosystem balance" },
  { id: "eco-2", categoryId: "eco", title: "The feasibility of transitioning to a 100% renewable energy grid" },
  { id: "eco-3", categoryId: "eco", title: "Coral bleaching and the collapse of marine biodiversity" },
  { id: "eco-4", categoryId: "eco", title: "The environmental impact of cryptocurrency mining" },
  { id: "eco-5", categoryId: "eco", title: "Regenerative agriculture vs. industrial farming" },
  { id: "eco-6", categoryId: "eco", title: "The geopolitics of fresh water scarcity" },
  { id: "eco-7", categoryId: "eco", title: "Geoengineering: Should we artificially cool the planet?" },
  { id: "eco-8", categoryId: "eco", title: "The mechanics of carbon capture and storage technologies" },
  { id: "eco-9", categoryId: "eco", title: "The truth behind recycling and global waste management" },
  { id: "eco-10", categoryId: "eco", title: "Invasive species and their disruption of local biomes" },
  { id: "eco-11", categoryId: "eco", title: "The ecological importance of the Amazon rainforest" },
  { id: "eco-12", categoryId: "eco", title: "Urban sprawl and the loss of natural habitats" },
  { id: "eco-13", categoryId: "eco", title: "The impact of fast fashion on global water supplies" },
  { id: "eco-14", categoryId: "eco", title: "The concept of a circular economy" },
  { id: "eco-15", categoryId: "eco", title: "Permafrost melting and the release of ancient trapped gases" },

  // --- 15. MEDICINE & HEALTH ---
  { id: "med-1", categoryId: "med", title: "The ethical dilemmas of organ transplantation and allocation" },
  { id: "med-2", categoryId: "med", title: "The mRNA vaccine revolution and its future applications" },
  { id: "med-3", categoryId: "med", title: "The integration of AI in diagnostic radiology" },
  { id: "med-4", categoryId: "med", title: "The history and eradication of smallpox" },
  { id: "med-5", categoryId: "med", title: "The physical consequences of a sedentary lifestyle" },
  { id: "med-6", categoryId: "med", title: "Psychedelics in the treatment of PTSD and depression" },
  { id: "med-7", categoryId: "med", title: "The science of longevity and anti-aging therapies" },
  { id: "med-8", categoryId: "med", title: "The over-prescription of opioids and the ensuing crisis" },
  { id: "med-9", categoryId: "med", title: "The blood-brain barrier and the challenge of neuro-pharmacology" },
  { id: "med-10", categoryId: "med", title: "The mechanics of autoimmune diseases" },
  { id: "med-11", categoryId: "med", title: "Telemedicine and the future of healthcare accessibility" },
  { id: "med-12", categoryId: "med", title: "The impact of ultra-processed foods on human health" },
  { id: "med-13", categoryId: "med", title: "The ethics of conducting clinical trials in developing nations" },
  { id: "med-14", categoryId: "med", title: "Stem cell research and regenerative medicine" },
  { id: "med-15", categoryId: "med", title: "The role of public health infrastructure in pandemic preparedness" },

  // --- 16. POLITICAL SCIENCE ---
  { id: "pol-1", categoryId: "pol", title: "The differences between direct and representative democracy" },
  { id: "pol-2", categoryId: "pol", title: "The role of the United Nations in preventing global conflict" },
  { id: "pol-3", categoryId: "pol", title: "Gerrymandering and the manipulation of electoral borders" },
  { id: "pol-4", categoryId: "pol", title: "The political philosophy of anarchism" },
  { id: "pol-5", categoryId: "pol", title: "The impact of lobbying and corporate PACs on legislation" },
  { id: "pol-6", categoryId: "pol", title: "Soft power vs. hard power in international relations" },
  { id: "pol-7", categoryId: "pol", title: "The mechanics of authoritarianism and censorship" },
  { id: "pol-8", categoryId: "pol", title: "The concept of the social contract by Hobbes and Rousseau" },
  { id: "pol-9", categoryId: "pol", title: "Populism and the appeal of anti-establishment candidates" },
  { id: "pol-10", categoryId: "pol", title: "The role of the media as the Fourth Estate" },
  { id: "pol-11", categoryId: "pol", title: "The theory of mutual assured destruction (MAD)" },
  { id: "pol-12", categoryId: "pol", title: "The challenges of implementing ranked-choice voting" },
  { id: "pol-13", categoryId: "pol", title: "Separatist movements and the right to self-determination" },
  { id: "pol-14", categoryId: "pol", title: "The evolution of the welfare state" },
  { id: "pol-15", categoryId: "pol", title: "The geopolitical significance of the Arctic region" },

  // --- 17. LAW & ETHICS ---
  { id: "law-1", categoryId: "law", title: "The ethics of intellectual property in the age of AI" },
  { id: "law-2", categoryId: "law", title: "The debate over the death penalty and restorative justice" },
  { id: "law-3", categoryId: "law", title: "The right to privacy vs. national security surveillance" },
  { id: "law-4", categoryId: "law", title: "The legal complexities of space exploration and colonization" },
  { id: "law-5", categoryId: "law", title: "The 'Right to be Forgotten' on the internet" },
  { id: "law-6", categoryId: "law", title: "Corporate personhood and liability" },
  { id: "law-7", categoryId: "law", title: "The ethics of whistleblower protections vs. corporate NDAs" },
  { id: "law-8", categoryId: "law", title: "The legality of deep-sea mining in international waters" },
  { id: "law-9", categoryId: "law", title: "Defamation laws in the era of anonymous social media" },
  { id: "law-10", categoryId: "law", title: "The debate around the legalization of illicit substances" },
  { id: "law-11", categoryId: "law", title: "The concept of eminent domain and property rights" },
  { id: "law-12", categoryId: "law", title: "Legal frameworks for autonomous vehicle liabilities" },
  { id: "law-13", categoryId: "law", title: "The ethics of genetic patenting" },
  { id: "law-14", categoryId: "law", title: "The role of the International Criminal Court (ICC)" },
  { id: "law-15", categoryId: "law", title: "The balance between free speech and hate speech regulations" },

  // --- 18. MUSIC & SOUND ---
  { id: "mus-1", categoryId: "mus", title: "The psychological impact of high-BPM energetic music on productivity" },
  { id: "mus-2", categoryId: "mus", title: "The physics of acoustics and soundwave propagation" },
  { id: "mus-3", categoryId: "mus", title: "The mathematics of musical scales and tuning systems" },
  { id: "mus-4", categoryId: "mus", title: "How streaming algorithms have changed pop song structures" },
  { id: "mus-5", categoryId: "mus", title: "The history and evolution of electronic synthesisers" },
  { id: "mus-6", categoryId: "mus", title: "The cultural significance of sampling in hip-hop production" },
  { id: "mus-7", categoryId: "mus", title: "Synesthesia: Experiencing sound as color" },
  { id: "mus-8", categoryId: "mus", title: "The use of binaural beats for cognitive enhancement" },
  { id: "mus-9", categoryId: "mus", title: "The impact of the loudness war on audio mastering" },
  { id: "mus-10", categoryId: "mus", title: "How film scoring manipulates audience emotions" },
  { id: "mus-11", categoryId: "mus", title: "The technological evolution from vinyl to lossless streaming" },
  { id: "mus-12", categoryId: "mus", title: "The role of silence and rests in musical composition" },
  { id: "mus-13", categoryId: "mus", title: "The psychology of earworms: Why songs get stuck in your head" },
  { id: "mus-14", categoryId: "mus", title: "The architecture of concert halls for optimal acoustics" },
  { id: "mus-15", categoryId: "mus", title: "AI-generated music and the future of artist royalties" },

  // --- 19. ENTERTAINMENT & MEDIA ---
  { id: "pop-1", categoryId: "pop", title: "The psychological appeal of the crime thriller genre" },
  { id: "pop-2", categoryId: "pop", title: "The cultural impact and business model of superhero cinematic universes" },
  { id: "pop-3", categoryId: "pop", title: "The evolution of reality television and voyeurism" },
  { id: "pop-4", categoryId: "pop", title: "The economics of free-to-play mobile games and microtransactions" },
  { id: "pop-5", categoryId: "pop", title: "The shift from episodic television to binge-watching culture" },
  { id: "pop-6", categoryId: "pop", title: "The rise of eSports and competitive gaming as mainstream entertainment" },
  { id: "pop-7", categoryId: "pop", title: "The mechanics of viral trends on short-form video platforms" },
  { id: "pop-8", categoryId: "pop", title: "The nostalgia cycle in Hollywood reboots and remakes" },
  { id: "pop-9", categoryId: "pop", title: "The blurring line between influencers and traditional celebrities" },
  { id: "pop-10", categoryId: "pop", title: "The impact of CGI overuse on suspension of disbelief in cinema" },
  { id: "pop-11", categoryId: "pop", title: "The narrative complexities of modern tabletop role-playing games" },
  { id: "pop-12", categoryId: "pop", title: "The transition of anime from niche subculture to global phenomenon" },
  { id: "pop-13", categoryId: "pop", title: "The psychology of horror movies and safe fear" },
  { id: "pop-14", categoryId: "pop", title: "The role of fandoms in dictating media production" },
  { id: "pop-15", categoryId: "pop", title: "The history and evolution of the comic book industry" },

  // --- 20. PRODUCTIVITY & SYSTEMS ---
  { id: "prod-1", categoryId: "prod", title: "The Pomodoro technique vs. flow-state time blocking" },
  { id: "prod-2", categoryId: "prod", title: "The Zettelkasten method for personal knowledge management" },
  { id: "prod-3", categoryId: "prod", title: "The Two-Minute Rule and overcoming task paralysis" },
  { id: "prod-4", categoryId: "prod", title: "The Eisenhower Matrix for prioritizing urgent vs. important tasks" },
  { id: "prod-5", categoryId: "prod", title: "The illusion of multitasking and cognitive switching penalties" },
  { id: "prod-6", categoryId: "prod", title: "Parkinson's Law: Work expands to fill the time allotted" },
  { id: "prod-7", categoryId: "prod", title: "The psychology of habit stacking and compounding routines" },
  { id: "prod-8", categoryId: "prod", title: "The impact of minimalist workspace design on focus" },
  { id: "prod-9", categoryId: "prod", title: "The Pareto Principle (80/20 rule) in daily workflows" },
  { id: "prod-10", categoryId: "prod", title: "Digital decluttering and inbox zero philosophies" },
  { id: "prod-11", categoryId: "prod", title: "The concept of 'Deep Work' in a distracted world" },
  { id: "prod-12", categoryId: "prod", title: "The pros and cons of gamifying your task list" },
  { id: "prod-13", categoryId: "prod", title: "The impact of sleep optimization on daily cognitive output" },
  { id: "prod-14", categoryId: "prod", title: "The role of accountability partners in achieving goals" },
  { id: "prod-15", categoryId: "prod", title: "Systemic thinking vs. goal-oriented thinking" },


  // --- 21. WEB ENGINEERING & ARCHITECTURE ---
  { id: "webdev-1", categoryId: "webdev", title: "Real-time state synchronization via WebSocket connections" },
  { id: "webdev-2", categoryId: "webdev", title: "The mechanics of automated WCAG compliance and accessibility analyzers" },
  { id: "webdev-3", categoryId: "webdev", title: "Server-side rendering vs. static site generation in Next.js" },
  { id: "webdev-4", categoryId: "webdev", title: "Designing robust database schemas using UUIDs vs. sequential IDs" },
  { id: "webdev-5", categoryId: "webdev", title: "The architecture of full-stack AI-powered web platforms" },
  { id: "webdev-6", categoryId: "webdev", title: "Implementing secure OAuth and session management via NextAuth" },
  { id: "webdev-7", categoryId: "webdev", title: "The evolution of CSS: From floats to Grid and utility classes" },
  { id: "webdev-8", categoryId: "webdev", title: "Micro-frontends and scaling large engineering teams" },
  { id: "webdev-9", categoryId: "webdev", title: "The performance costs of heavy JavaScript hydration" },
  { id: "webdev-10", categoryId: "webdev", title: "Building scalable audio and media streaming backend logic" },
  { id: "webdev-11", categoryId: "webdev", title: "The shift toward Edge computing and serverless architectures" },
  { id: "webdev-12", categoryId: "webdev", title: "Optimizing relational database queries and indexing" },
  { id: "webdev-13", categoryId: "webdev", title: "The principles of idempotent API design" },
  { id: "webdev-14", categoryId: "webdev", title: "Handling sub-100ms latency in real-time chat applications" },
  { id: "webdev-15", categoryId: "webdev", title: "The role of service workers in Progressive Web Apps (PWAs)" },

  // --- 22. ALGORITHMS & COMPUTATION ---
  { id: "algo-1", categoryId: "algo", title: "Graph programming patterns and traversal algorithms" },
  { id: "algo-2", categoryId: "algo", title: "Time and space complexity optimization in competitive programming" },
  { id: "algo-3", categoryId: "algo", title: "The mechanics of dynamic programming and memoization" },
  { id: "algo-4", categoryId: "algo", title: "Divide and conquer strategies in sorting algorithms" },
  { id: "algo-5", categoryId: "algo", title: "Heuristic search algorithms in artificial intelligence" },
  { id: "algo-6", categoryId: "algo", title: "The role of hash tables in achieving O(1) lookups" },
  { id: "algo-7", categoryId: "algo", title: "Binary search trees and self-balancing data structures" },
  { id: "algo-8", categoryId: "algo", title: "Bit manipulation techniques for memory-constrained environments" },
  { id: "algo-9", categoryId: "algo", title: "String matching algorithms (KMP, Rabin-Karp)" },
  { id: "algo-10", categoryId: "algo", title: "The mathematics of Big O notation" },
  { id: "algo-11", categoryId: "algo", title: "Greedy algorithms vs. exhaustive search methods" },
  { id: "algo-12", categoryId: "algo", title: "Topological sorting in dependency resolution" },
  { id: "algo-13", categoryId: "algo", title: "The implementation of priority queues using Heaps" },
  { id: "algo-14", categoryId: "algo", title: "Pathfinding algorithms (A* vs. Dijkstra) in navigation systems" },
  { id: "algo-15", categoryId: "algo", title: "The architecture of algorithmic recommendation engines" },

  // --- 23. CYBERSECURITY & PRIVACY ---
  { id: "cyber-1", categoryId: "cyber", title: "The ecosystem of data brokers and online privacy exposure" },
  { id: "cyber-2", categoryId: "cyber", title: "Network security architectures and perimeter defense" },
  { id: "cyber-3", categoryId: "cyber", title: "The mechanics of end-to-end encryption protocols" },
  { id: "cyber-4", categoryId: "cyber", title: "Social engineering and the human element of cybersecurity" },
  { id: "cyber-5", categoryId: "cyber", title: "Zero-day vulnerabilities and the exploit economy" },
  { id: "cyber-6", categoryId: "cyber", title: "The architecture of Distributed Denial of Service (DDoS) attacks" },
  { id: "cyber-7", categoryId: "cyber", title: "Ransomware syndicates and decentralized payment tracking" },
  { id: "cyber-8", categoryId: "cyber", title: "The role of digital forensics in incident response" },
  { id: "cyber-9", categoryId: "cyber", title: "Identity and Access Management (IAM) in enterprise networks" },
  { id: "cyber-10", categoryId: "cyber", title: "The vulnerabilities of smart home IoT devices" },
  { id: "cyber-11", categoryId: "cyber", title: "State-sponsored cyber warfare and critical infrastructure" },
  { id: "cyber-12", categoryId: "cyber", title: "The mechanics of biometric authentication hacking" },
  { id: "cyber-13", categoryId: "cyber", title: "Hardware-level security flaws (Spectre and Meltdown)" },
  { id: "cyber-14", categoryId: "cyber", title: "The challenge of securing global supply chains" },
  { id: "cyber-15", categoryId: "cyber", title: "The legal right to digital anonymity" },

  // --- 24. BLOCKCHAIN & DECENTRALIZATION ---
  { id: "web3-1", categoryId: "web3", title: "The mechanics of decentralized quadratic crowdfunding" },
  { id: "web3-2", categoryId: "web3", title: "Writing secure Solidity smart contracts for web3 applications" },
  { id: "web3-3", categoryId: "web3", title: "The integration of Web3 interfaces using Ethers.js and MetaMask" },
  { id: "web3-4", categoryId: "web3", title: "Proof of Work vs. Proof of Stake consensus mechanisms" },
  { id: "web3-5", categoryId: "web3", title: "The vulnerabilities of smart contract reentrancy attacks" },
  { id: "web3-6", categoryId: "web3", title: "Decentralized Autonomous Organizations (DAOs) and governance" },
  { id: "web3-7", categoryId: "web3", title: "The economics of automated market makers (AMMs)" },
  { id: "web3-8", categoryId: "web3", title: "Layer 2 scaling solutions (Rollups and sidechains)" },
  { id: "web3-9", categoryId: "web3", title: "Non-Fungible Tokens (NFTs) beyond digital art" },
  { id: "web3-10", categoryId: "web3", title: "The concept of decentralized physical infrastructure networks (DePIN)" },
  { id: "web3-11", categoryId: "web3", title: "The Oracle problem: Connecting smart contracts to real-world data" },
  { id: "web3-12", categoryId: "web3", title: "Central Bank Digital Currencies (CBDCs) vs. public blockchains" },
  { id: "web3-13", categoryId: "web3", title: "The mechanics of flash loans and decentralized arbitrage" },
  { id: "web3-14", categoryId: "web3", title: "Tokenomics and sustainable digital economies" },
  { id: "web3-15", categoryId: "web3", title: "The challenge of cross-chain interoperability" },

  // --- 25. GEOGRAPHY & URBANISM ---
  { id: "travel-1", categoryId: "travel", title: "The impact of crowdsourced local mapping and digital guides" },
  { id: "travel-2", categoryId: "travel", title: "The privacy implications of persistent spatial timeline tracking" },
  { id: "travel-3", categoryId: "travel", title: "The 15-minute city concept in modern urban planning" },
  { id: "travel-4", categoryId: "travel", title: "How global geography dictates economic prosperity" },
  { id: "travel-5", categoryId: "travel", title: "The engineering of high-speed rail networks" },
  { id: "travel-6", categoryId: "travel", title: "Overtourism and the degradation of historical landmarks" },
  { id: "travel-7", categoryId: "travel", title: "The design of walkable cities vs. car-centric infrastructure" },
  { id: "travel-8", categoryId: "travel", title: "The geopolitics of navigable river systems" },
  { id: "travel-9", categoryId: "travel", title: "Adaptive reuse of industrial spaces in urban centers" },
  { id: "travel-10", categoryId: "travel", title: "The phenomenon of urban heat islands" },
  { id: "travel-11", categoryId: "travel", title: "The logistics of global shipping chokepoints (e.g., Suez Canal)" },
  { id: "travel-12", categoryId: "travel", title: "The cultural significance of public squares and plazas" },
  { id: "travel-13", categoryId: "travel", title: "The mechanics of global air traffic control networks" },
  { id: "travel-14", categoryId: "travel", title: "The preservation of languages in isolated geographic regions" },
  { id: "travel-15", categoryId: "travel", title: "The impact of rising sea levels on coastal megacities" },

  // --- 26. GAME DESIGN & MECHANICS ---
  { id: "game-1", categoryId: "game", title: "The economics of microtransactions, level-up packages, and special airdrops" },
  { id: "game-2", categoryId: "game", title: "Matchmaking algorithms in competitive multiplayer arenas" },
  { id: "game-3", categoryId: "game", title: "The psychology of loot boxes and intermittent reinforcement" },
  { id: "game-4", categoryId: "game", title: "Procedural generation in expansive open-world games" },
  { id: "game-5", categoryId: "game", title: "The evolution of the Battle Royale genre" },
  { id: "game-6", categoryId: "game", title: "Ludonarrative dissonance: When gameplay contradicts the story" },
  { id: "game-7", categoryId: "game", title: "The concept of 'Juice' (game feel) in user feedback systems" },
  { id: "game-8", categoryId: "game", title: "Designing skill trees and meaningful progression systems" },
  { id: "game-9", categoryId: "game", title: "The mathematics of game balancing and avoiding power creep" },
  { id: "game-10", categoryId: "game", title: "The transition from physical media to cloud gaming" },
  { id: "game-11", categoryId: "game", title: "The cultural phenomenon of digital cosmetic skins" },
  { id: "game-12", categoryId: "game", title: "The use of environmental storytelling over cutscenes" },
  { id: "game-13", categoryId: "game", title: "Asynchronous multiplayer mechanics" },
  { id: "game-14", categoryId: "game", title: "The challenge of designing intuitive user interfaces for complex HUDs" },
  { id: "game-15", categoryId: "game", title: "The integration of AI NPCs and dynamic dialogue systems" },

  // --- 27. FOOD SCIENCE & GASTRONOMY ---
  { id: "food-1", categoryId: "food", title: "The operational dynamics of cloud kitchens and localized food delivery" },
  { id: "food-2", categoryId: "food", title: "The historical and cultural evolution of regional Biryani" },
  { id: "food-3", categoryId: "food", title: "The Maillard reaction and the chemistry of cooking" },
  { id: "food-4", categoryId: "food", title: "The logistics of the global spice trade" },
  { id: "food-5", categoryId: "food", title: "The science of fermentation in culinary traditions" },
  { id: "food-6", categoryId: "food", title: "The psychological impact of menu design and pricing psychology" },
  { id: "food-7", categoryId: "food", title: "The environmental impact of mass meat production" },
  { id: "food-8", categoryId: "food", title: "The rise of lab-grown meats and cellular agriculture" },
  { id: "food-9", categoryId: "food", title: "The preservation techniques that allowed ancient sea travel" },
  { id: "food-10", categoryId: "food", title: "The cultural significance of street food ecosystems" },
  { id: "food-11", categoryId: "food", title: "The chemistry of emulsification and sauces" },
  { id: "food-12", categoryId: "food", title: "The history of caffeine and its role in the Industrial Revolution" },
  { id: "food-13", categoryId: "food", title: "The impact of fast-food franchising on global diets" },
  { id: "food-14", categoryId: "food", title: "The genetic modification of modern agricultural crops" },
  { id: "food-15", categoryId: "food", title: "The role of olfactory senses in taste perception" },

  // --- 28. MYTHOLOGY & FOLKLORE ---
  { id: "myth-1", categoryId: "myth", title: "The evolution of the modern superhero as contemporary mythology" },
  { id: "myth-2", categoryId: "myth", title: "The shared flood myth across ancient civilizations" },
  { id: "myth-3", categoryId: "myth", title: "The archetype of the Trickster in global folklore" },
  { id: "myth-4", categoryId: "myth", title: "The role of mythology in explaining natural phenomena" },
  { id: "myth-5", categoryId: "myth", title: "High fantasy tropes and their roots in European folklore" },
  { id: "myth-6", categoryId: "myth", title: "The structural similarities of the Greek and Roman pantheons" },
  { id: "myth-7", categoryId: "myth", title: "The concept of Valhalla and Norse eschatology (Ragnarök)" },
  { id: "myth-8", categoryId: "myth", title: "The symbolism of dragons in Eastern vs. Western mythology" },
  { id: "myth-9", categoryId: "myth", title: "Urban legends and the modern transmission of folklore" },
  { id: "myth-10", categoryId: "myth", title: "The significance of the underworld in ancient religions" },
  { id: "myth-11", categoryId: "myth", title: "The incorporation of mythological figures into branding and logos" },
  { id: "myth-12", categoryId: "myth", title: "The folklore surrounding cryptids and uncharted wilderness" },
  { id: "myth-13", categoryId: "myth", title: "The transition from polytheism to monotheism in antiquity" },
  { id: "myth-14", categoryId: "myth", title: "The role of oral storytelling in preserving cultural identity" },
  { id: "myth-15", categoryId: "myth", title: "The hero's journey in modern cinema and literature" },

  // --- 29. STARTUPS & INNOVATION ---
  { id: "biz-1", categoryId: "biz", title: "The mechanics of modern talent sourcing and recruitment platforms" },
  { id: "biz-2", categoryId: "biz", title: "The lean startup methodology and the MVP (Minimum Viable Product)" },
  { id: "biz-3", categoryId: "biz", title: "Bootstrapping vs. Venture Capital funding" },
  { id: "biz-4", categoryId: "biz", title: "The psychology of product-market fit" },
  { id: "biz-5", categoryId: "biz", title: "The economics of the Software as a Service (SaaS) subscription model" },
  { id: "biz-6", categoryId: "biz", title: "Customer acquisition cost (CAC) vs. Lifetime value (LTV)" },
  { id: "biz-7", categoryId: "biz", title: "The challenge of scaling company culture during hyper-growth" },
  { id: "biz-8", categoryId: "biz", title: "Disruptive innovation and the innovator's dilemma" },
  { id: "biz-9", categoryId: "biz", title: "The gig economy and the unbundling of traditional employment" },
  { id: "biz-10", categoryId: "biz", title: "Network effects and the winner-take-all market dynamics" },
  { id: "biz-11", categoryId: "biz", title: "The impact of hackathons on rapid product prototyping" },
  { id: "biz-12", categoryId: "biz", title: "The role of open-source projects in B2B business models" },
  { id: "biz-13", categoryId: "biz", title: "Pivoting strategies when initial business models fail" },
  { id: "biz-14", categoryId: "biz", title: "The ethics of aggressive growth hacking" },
  { id: "biz-15", categoryId: "biz", title: "The transition from Web2 enterprise solutions to decentralized infrastructure" },

  // --- 30. AEROSPACE & ENGINEERING ---
  { id: "space-1", categoryId: "space", title: "The engineering mechanics of reusable rocket boosters" },
  { id: "space-2", categoryId: "space", title: "The challenges of mitigating orbital space debris (Kessler Syndrome)" },
  { id: "space-3", categoryId: "space", title: "The physics of orbital mechanics and Hohmann transfer orbits" },
  { id: "space-4", categoryId: "space", title: "The design architecture of the James Webb Space Telescope" },
  { id: "space-5", categoryId: "space", title: "The physiological effects of long-term microgravity on the human body" },
  { id: "space-6", categoryId: "space", title: "The feasibility of asteroid mining for rare earth metals" },
  { id: "space-7", categoryId: "space", title: "The aerodynamics of supersonic and hypersonic flight" },
  { id: "space-8", categoryId: "space", title: "The technology behind ion thrusters for deep space probes" },
  { id: "space-9", categoryId: "space", title: "The communication lag and data transmission in interplanetary missions" },
  { id: "space-10", categoryId: "space", title: "The history of the Apollo Guidance Computer" },
  { id: "space-11", categoryId: "space", title: "The geopolitics of the modern commercial space race" },
  { id: "space-12", categoryId: "space", title: "The concept and engineering barriers of a Space Elevator" },
  { id: "space-13", categoryId: "space", title: "The role of Lagrange points in placing space observatories" },
  { id: "space-14", categoryId: "space", title: "The engineering of heat shields for atmospheric reentry" },
  { id: "space-15", categoryId: "space", title: "The future of nuclear thermal propulsion for spacecraft" }
];

export const getRandomTopicByCategory = (categoryId: string): Topic | null => {
  let availableTopics = topics;
  
  if (categoryId !== "all") {
    availableTopics = topics.filter(topic => topic.categoryId === categoryId);
  }

  if (availableTopics.length === 0) return null; 

  const randomIndex = Math.floor(Math.random() * availableTopics.length);
  return availableTopics[randomIndex];
};